[tools]
# Basic Languages
ruby = "latest"
go = "latest"

# node
node = "24"
aube = "latest"
deno = "latest"
"npm:pnpm" = "latest"
"npm:agent-browser" = "latest"
"npm:portless" = "latest"
"npm:@openai/codex" = "latest"

# python
python = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
"pipx:yt-dlp" = { version = "latest", extras = "default" }

# Other cli
gh = "latest"
aws-cli = "latest"
gcloud = "latest"
jq = "latest"
fzf = "latest"

[settings]
experimental = true
ruby.compile = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["ruby", "python"]
