[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplcache.vim'
disabled = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-fugitive' 

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

