[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplcache.vim'
disabled = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

# endの補完等
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-fugitive' 

# ANSI情報を色付け
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# -でメソッドの効果を反転
[[plugins]]
repo = 'AndrewRadev/switch.vim'

# gccでコメント/コメントアウトを入れ替え
[[plugins]]
repo = 'tomtom/tcomment_vim'

# シングルクオートとダブルクオートの入れ替え等
[[plugins]]
repo = 'tpope/vim-surround'
